#!/usr/bin/env ruby

require "the_path"

subcommand = ARGV.shift

if subcommand == "help" || subcommand == "-h"
  puts "To create a new repo, type 'the_path init' from an empty directory."
  puts "  To sync to your MailChimp account, type 'the_path init' from a repository."
  puts "  Automations not beginning with the_path emoji won't be affected."
  puts "  But please make sure you're not overwriting more recent automations with "
  puts "  older content! For more documentation,"
  puts "  see https://github.com/noahgibbs/the_path"
  exit 0
end

SUBCOMMANDS = {
  "init" => ThePath::InitCommand,
  "sync" => ThePath::SyncCommand,
  "backup" => ThePath::BackupCommand,
  "peek" => ThePath::PeekCommand,
}

if SUBCOMMANDS[subcommand]
  command_object = SUBCOMMANDS[subcommand].new
  command_object.run
  exit 0
end

STDERR.puts "Unrecognized command: #{subcommand.inspect}!"
STDERR.puts "  For usage instructions, type 'the_path help' or 'the_path -h'"
exit -1
